In [13]:
my_list = [1,2,3,4,'h',5]

In [2]:
my_list = iter(my_list)
type(my_list)

list_iterator

In [11]:
next(my_list)

StopIteration: 

In [14]:
for item in my_list:
    print(item)

1
2
3
4
h
5


In [15]:
my_list = iter(my_list)
iterating = True

while iterating:
    try:
        item = next(my_list)
    except StopIteration:
        iterating = False
    else:
        print(item)

1
2
3
4
h
5


In [16]:
import numpy as np

a = np.arange(20)

In [17]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
a = a.reshape(5, 4)

In [19]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [20]:
a.mean()

9.5

In [23]:
a.mean(axis=0) #mean of every column

array([ 8.,  9., 10., 11.])

In [24]:
a.mean(axis=1) #mean of every row

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [25]:
a[:4, :] #first four rows, every column

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
a[:4, 2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [28]:
a[:4, 2:4].mean(1) # takes mean of rows of this section

array([ 2.5,  6.5, 10.5, 14.5])

In [35]:
import pandas as pd
df = pd.read_csv('/Users/natimarcus/Desktop/GA2/titanic.csv') #find by clicking on file in finder and typing option-command-c

In [36]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [37]:
df.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

In [38]:
df.shape # (rows, columns)

(891, 12)

In [39]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [40]:
df.mean()

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [41]:
np.mean(df)

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [43]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
5       NaN
6      54.0
7       2.0
8      27.0
9      14.0
10      4.0
11     58.0
12     20.0
13     39.0
14     14.0
15     55.0
16      2.0
17      NaN
18     31.0
19      NaN
20     35.0
21     34.0
22     15.0
23     28.0
24      8.0
25     38.0
26      NaN
27     19.0
28      NaN
29      NaN
       ... 
861    21.0
862    48.0
863     NaN
864    24.0
865    42.0
866    27.0
867    31.0
868     NaN
869     4.0
870    26.0
871    47.0
872    33.0
873    47.0
874    28.0
875    15.0
876    20.0
877    19.0
878     NaN
879    56.0
880    25.0
881    33.0
882    22.0
883    28.0
884    25.0
885    39.0
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [44]:
df['Age'][:100]

0     22.00
1     38.00
2     26.00
3     35.00
4     35.00
5       NaN
6     54.00
7      2.00
8     27.00
9     14.00
10     4.00
11    58.00
12    20.00
13    39.00
14    14.00
15    55.00
16     2.00
17      NaN
18    31.00
19      NaN
20    35.00
21    34.00
22    15.00
23    28.00
24     8.00
25    38.00
26      NaN
27    19.00
28      NaN
29      NaN
      ...  
70    32.00
71    16.00
72    21.00
73    26.00
74    32.00
75    25.00
76      NaN
77      NaN
78     0.83
79    30.00
80    22.00
81    29.00
82      NaN
83    28.00
84    17.00
85    33.00
86    16.00
87      NaN
88    23.00
89    24.00
90    29.00
91    20.00
92    46.00
93    26.00
94    59.00
95      NaN
96    71.00
97    23.00
98    34.00
99    34.00
Name: Age, Length: 100, dtype: float64

In [45]:
df['Age'][:100].mean()

27.46576923076923

In [46]:
df[['Name', 'Age', 'Fare']]

Name   Age      Fare
0                              Braund, Mr. Owen Harris  22.0    7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0   71.2833
2                               Heikkinen, Miss. Laina  26.0    7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0   53.1000
4                             Allen, Mr. William Henry  35.0    8.0500
5                                     Moran, Mr. James   NaN    8.4583
6                              McCarthy, Mr. Timothy J  54.0   51.8625
7                       Palsson, Master. Gosta Leonard   2.0   21.0750
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0   11.1333
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0   30.0708
10                     Sandstrom, Miss. Marguerite Rut   4.0   16.7000
11                            Bonnell, Miss. Elizabeth  58.0   26.5500
12                      Saundercock, Mr. William Henry  20.0    8.0500
13                         Andersson, Mr. Anders Johan  39.0   31.2750
14                Vestrom, Miss. Hulda Amanda Adolfina  14.0    7.8542
15                    Hewlett, Mrs. (Mary D Kingcome)   55.0   16.0000
16                                Rice, Master. Eugene   2.0   29.1250
17                        Williams, Mr. Charles Eugene   NaN   13.0000
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  31.0   18.0000
19                             Masselmani, Mrs. Fatima   NaN    7.2250
20                                Fynney, Mr. Joseph J  35.0   26.0000
21                               Beesley, Mr. Lawrence  34.0   13.0000
22                         McGowan, Miss. Anna "Annie"  15.0    8.0292
23                        Sloper, Mr. William Thompson  28.0   35.5000
24                       Palsson, Miss. Torborg Danira   8.0   21.0750
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  38.0   31.3875
26                             Emir, Mr. Farred Chehab   NaN    7.2250
27                      Fortune, Mr. Charles Alexander  19.0  263.0000
28                       O'Dwyer, Miss. Ellen "Nellie"   NaN    7.8792
29                                 Todoroff, Mr. Lalio   NaN    7.8958
..                                                 ...   ...       ...
861                        Giles, Mr. Frederick Edward  21.0   11.5000
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  48.0   25.9292
863                  Sage, Miss. Dorothy Edith "Dolly"   NaN   69.5500
864                             Gill, Mr. John William  24.0   13.0000
865                           Bystrom, Mrs. (Karolina)  42.0   13.0000
866                       Duran y More, Miss. Asuncion  27.0   13.8583
867               Roebling, Mr. Washington Augustus II  31.0   50.4958
868                        van Melkebeke, Mr. Philemon   NaN    9.5000
869                    Johnson, Master. Harold Theodor   4.0   11.1333
870                                  Balkic, Mr. Cerin  26.0    7.8958
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0   52.5542
872                           Carlsson, Mr. Frans Olof  33.0    5.0000
873                        Vander Cruyssen, Mr. Victor  47.0    9.0000
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0   24.0000
875                   Najib, Miss. Adele Kiamie "Jane"  15.0    7.2250
876                      Gustafsson, Mr. Alfred Ossian  20.0    9.8458
877                               Petroff, Mr. Nedelio  19.0    7.8958
878                                 Laleff, Mr. Kristo   NaN    7.8958
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0   83.1583
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0   26.0000
881                                 Markun, Mr. Johann  33.0    7.8958
882                       Dahlberg, Miss. Gerda Ulrika  22.0   10.5167
883                      Banfield, Mr. Frederick James  28.0   10.5000
884                             Sutehall, Mr. Henry Jr  25.0    7.0500
885               Rice, Mrs. William (Margaret Norton)  39.0   29.1250
886

In [48]:
df[['Name', 'Age', 'Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [49]:
df['Age'].nsmallest(5)

803    0.42
755    0.67
469    0.75
644    0.75
78     0.83
Name: Age, dtype: float64

In [50]:
df.iloc[2:7, [2, 6, 9]] #rows 2-7 (not including 7) and columns 2, 6, and 9

Pclass  SibSp     Fare
2       3      0   7.9250
3       1      1  53.1000
4       3      0   8.0500
5       3      0   8.4583
6       1      0  51.8625

In [51]:
df.Age > 25

0      False
1       True
2       True
3       True
4       True
5      False
6       True
7      False
8       True
9      False
10     False
11      True
12     False
13      True
14     False
15      True
16     False
17     False
18      True
19     False
20      True
21      True
22     False
23      True
24     False
25      True
26     False
27     False
28     False
29     False
       ...  
861    False
862     True
863    False
864    False
865     True
866     True
867     True
868    False
869    False
870     True
871     True
872     True
873     True
874     True
875    False
876    False
877    False
878    False
879     True
880    False
881     True
882    False
883     True
884    False
885     True
886     True
887    False
888    False
889     True
890     True
Name: Age, Length: 891, dtype: bool

In [52]:
df[df.Age > 25]

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
8              9         1       3   
11            12         1       1   
13            14         0       3   
15            16         1       2   
18            19         0       3   
20            21         0       2   
21            22         1       2   
23            24         1       1   
25            26         1       3   
30            31         0       1   
33            34         0       2   
34            35         0       1   
35            36         0       1   
40            41         0       3   
41            42         0       2   
52            53         1       1   
53            54         1       2   
54            55         0       1   
57            58         0       3   
61            62         1       1   
62            63         0       1   
66            67         1       2   
69            70         0       3   
70            71         0       2   
73            74         0       3   
..           ...       ...     ...   
823          824         1       3   
829          830         1       1   
835          836         1       1   
838          839         1       3   
842          843         1       1   
843          844         0       3   
845          846         0       3   
847          848         0       3   
848          849         0       2   
851          852         0       3   
854          855         0       2   
856          857         1       1   
857          858         1       1   
860          861         0       3   
862          863         1       1   
865          866         1       2   
866          867         1       2   
867          868         0       1   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
879          880         1       1   
881          882         0       3   
883          884         0       2   
885          886         0       3   
886          887         0       2   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
20                                Fynney, Mr. Joseph J    male  35.0      0   
21                               Beesley, Mr. Lawrence    male  34.0      0   
23                        Sloper, Mr. William Thompson    male  28.0      0   
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0      1   
30                            Uruchurtu, Don. Manuel E    male  40.0      0   
33                               Wheadon, Mr. Edward H    male  66.0      0   
34                             Meyer, Mr. Edgar Joseph    male  28.0      1   
35                      Holverson, Mr. Alexander Oskar    male  42.0      1   
40      Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  40.0      1   
41   Turpin, Mrs. William John Robert (Dorothy Ann ...  female  27.0

In [53]:
df[df.Age > 25].iloc[:, :5]

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
8              9         1       3   
11            12         1       1   
13            14         0       3   
15            16         1       2   
18            19         0       3   
20            21         0       2   
21            22         1       2   
23            24         1       1   
25            26         1       3   
30            31         0       1   
33            34         0       2   
34            35         0       1   
35            36         0       1   
40            41         0       3   
41            42         0       2   
52            53         1       1   
53            54         1       2   
54            55         0       1   
57            58         0       3   
61            62         1       1   
62            63         0       1   
66            67         1       2   
69            70         0       3   
70            71         0       2   
73            74         0       3   
..           ...       ...     ...   
823          824         1       3   
829          830         1       1   
835          836         1       1   
838          839         1       3   
842          843         1       1   
843          844         0       3   
845          846         0       3   
847          848         0       3   
848          849         0       2   
851          852         0       3   
854          855         0       2   
856          857         1       1   
857          858         1       1   
860          861         0       3   
862          863         1       1   
865          866         1       2   
866          867         1       2   
867          868         0       1   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
879          880         1       1   
881          882         0       3   
883          884         0       2   
885          886         0       3   
886          887         0       2   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex  
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  
2                               Heikkinen, Miss. Laina  female  
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  
4                             Allen, Mr. William Henry    male  
6                              McCarthy, Mr. Timothy J    male  
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  
11                            Bonnell, Miss. Elizabeth  female  
13                         Andersson, Mr. Anders Johan    male  
15                    Hewlett, Mrs. (Mary D Kingcome)   female  
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  
20                                Fynney, Mr. Joseph J    male  
21                               Beesley, Mr. Lawrence    male  
23                        Sloper, Mr. William Thompson    male  
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  
30                            Uruchurtu, Don. Manuel E    male  
33                               Wheadon, Mr. Edward H    male  
34                             Meyer, Mr. Edgar Joseph    male  
35                      Holverson, Mr. Alexander Oskar    male  
40      Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  
41   Turpin, Mrs. William John Robert (Dorothy Ann ...  female  
52            Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  
53   Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  female  
54                      Ostby, Mr. Engelhart Cornelius    male  
57                                 Novel, Mr. Mansouer    male  
61                     

In [54]:
df[df.Age > 25].iloc[:, :5].mean()

PassengerId    455.331719
Survived         0.401937
Pclass           2.041162
dtype: float64

In [55]:
df[df.Age > 25]['Survived']

1      1
2      1
3      1
4      0
6      0
8      1
11     1
13     0
15     1
18     0
20     0
21     1
23     1
25     1
30     0
33     0
34     0
35     0
40     0
41     0
52     1
53     1
54     0
57     0
61     1
62     0
66     1
69     0
70     0
73     0
      ..
823    1
829    1
835    1
838    1
842    1
843    0
845    0
847    0
848    0
851    0
854    0
856    1
857    1
860    0
862    1
865    1
866    1
867    0
870    0
871    1
872    0
873    0
874    1
879    1
881    0
883    0
885    0
886    0
889    1
890    0
Name: Survived, Length: 413, dtype: int64

In [56]:
df[(df.Age > 25) | (df.Survived == 1)]

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
13            14         0       3   
15            16         1       2   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
25            26         1       3   
28            29         1       3   
30            31         0       1   
31            32         1       1   
32            33         1       3   
33            34         0       2   
34            35         0       1   
35            36         0       1   
36            37         1       3   
39            40         1       3   
40            41         0       3   
41            42         0       2   
..           ...       ...     ...   
848          849         0       2   
849          850         1       1   
851          852         0       3   
853          854         1       1   
854          855         0       2   
855          856         1       3   
856          857         1       1   
857          858         1       1   
858          859         1       3   
860          861         0       3   
862          863         1       1   
865          866         1       2   
866          867         1       2   
867          868         0       1   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
883          884         0       2   
885          886         0       3   
886          887         0       2   
887          888         1       1   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN      0   
20                                Fynney, Mr. Joseph J    male  35.0      0   
21                               Beesley, Mr. Lawrence    male  34.0      0   
22                         McGowan, Miss. Anna "Annie"  female  15.0      0   
23                        Sloper, Mr. William Thompson    male  28.0      0   
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0      1   
28                       O'Dwyer, Miss. Ellen "Nellie"  female   NaN

In [57]:
df[(df.Age > 25) & (df.Survived == 1)]

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
11            12         1       1   
15            16         1       2   
21            22         1       2   
23            24         1       1   
25            26         1       3   
52            53         1       1   
53            54         1       2   
61            62         1       1   
66            67         1       2   
74            75         1       3   
79            80         1       3   
81            82         1       3   
85            86         1       3   
98            99         1       2   
123          124         1       2   
133          134         1       2   
146          147         1       3   
161          162         1       2   
187          188         1       1   
190          191         1       2   
194          195         1       1   
195          196         1       1   
207          208         1       3   
209          210         1       1   
211          212         1       2   
215          216         1       1   
..           ...       ...     ...   
737          738         1       1   
744          745         1       3   
747          748         1       2   
754          755         1       2   
759          760         1       1   
763          764         1       1   
765          766         1       1   
774          775         1       2   
779          780         1       1   
796          797         1       1   
797          798         1       3   
801          802         1       2   
804          805         1       3   
809          810         1       1   
820          821         1       1   
821          822         1       3   
823          824         1       3   
829          830         1       1   
835          836         1       1   
838          839         1       3   
842          843         1       1   
856          857         1       1   
857          858         1       1   
862          863         1       1   
865          866         1       2   
866          867         1       2   
871          872         1       1   
874          875         1       2   
879          880         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
21                               Beesley, Mr. Lawrence    male  34.0      0   
23                        Sloper, Mr. William Thompson    male  28.0      0   
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0      1   
52            Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.0      1   
53   Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  female  29.0      1   
61                                 Icard, Miss. Amelie  female  38.0      0   
66                        Nye, Mrs. (Elizabeth Ramell)  female  29.0      0   
74                                       Bing, Mr. Lee    male  32.0      0   
79                            Dowdell, Miss. Elizabeth  female  30.0      0   
81                         Sheerlinck, Mr. Jan Baptist    male  29.0      0   
85   Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...  female  33.0      3   
98                Doling, Mrs. John T (Ada Julia Bone)  female  34.0      0   
123                                Webber, Miss. Susan  female  32.5      0   
133      Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0

In [58]:
df[(df.Sex == 'female') & (df.SibSp >= 1)]['Survived'].mean()

0.6857142857142857

In [59]:
np.round(df[(df.Sex == 'female') & (df.SibSp >= 1)]['Survived'].mean(),2)

0.69

In [60]:
df['Age']**2

0       484.0
1      1444.0
2       676.0
3      1225.0
4      1225.0
5         NaN
6      2916.0
7         4.0
8       729.0
9       196.0
10       16.0
11     3364.0
12      400.0
13     1521.0
14      196.0
15     3025.0
16        4.0
17        NaN
18      961.0
19        NaN
20     1225.0
21     1156.0
22      225.0
23      784.0
24       64.0
25     1444.0
26        NaN
27      361.0
28        NaN
29        NaN
        ...  
861     441.0
862    2304.0
863       NaN
864     576.0
865    1764.0
866     729.0
867     961.0
868       NaN
869      16.0
870     676.0
871    2209.0
872    1089.0
873    2209.0
874     784.0
875     225.0
876     400.0
877     361.0
878       NaN
879    3136.0
880     625.0
881    1089.0
882     484.0
883     784.0
884     625.0
885    1521.0
886     729.0
887     361.0
888       NaN
889     676.0
890    1024.0
Name: Age, Length: 891, dtype: float64

In [61]:
df['New Column'] = df['Age']**2

In [62]:
df['New Column']

0       484.0
1      1444.0
2       676.0
3      1225.0
4      1225.0
5         NaN
6      2916.0
7         4.0
8       729.0
9       196.0
10       16.0
11     3364.0
12      400.0
13     1521.0
14      196.0
15     3025.0
16        4.0
17        NaN
18      961.0
19        NaN
20     1225.0
21     1156.0
22      225.0
23      784.0
24       64.0
25     1444.0
26        NaN
27      361.0
28        NaN
29        NaN
        ...  
861     441.0
862    2304.0
863       NaN
864     576.0
865    1764.0
866     729.0
867     961.0
868       NaN
869      16.0
870     676.0
871    2209.0
872    1089.0
873    2209.0
874     784.0
875     225.0
876     400.0
877     361.0
878       NaN
879    3136.0
880     625.0
881    1089.0
882     484.0
883     784.0
884     625.0
885    1521.0
886     729.0
887     361.0
888       NaN
889     676.0
890    1024.0
Name: New Column, Length: 891, dtype: float64

In [63]:
df.drop('Age', inplace = True, axis = 1)